import type { BootstrapState } from "@vraxis/code-contracts";

export const emptyState: BootstrapState = {
  contractVersion: 26,
  projects: [],
  sessions: [],
  runtimes: [{
    id: "codex",
    name: "Codex CLI",
    availability: "installed",
    detail: "Ready",
    acceptsCustomModel: true,
    kind: "local-cli",
    version: "codex-cli 0.151.0",
    executable: "/usr/local/bin/codex",
    authentication: "authenticated",
    authenticationDetail: "Authenticated with ChatGPT.",
    modelDiscovery: "automatic",
    checkedAt: "2026-08-30T20:30:00.000Z",
    update: { status: "current", latestVersion: "0.151.0", detail: "Version 0.151.0 is current." },
    models: [{ id: "gpt-5.6-sol", name: "GPT-5.6-Sol", availability: "available", isDefault: true, description: "Latest frontier agentic coding model.", capabilities: ["text", "vision", "tools", "structured-output"], reasoningEfforts: ["low", "medium", "high", "xhigh", "max", "ultra"] }],
    capabilities: ["structured-output", "local-workspace", "read-only-workspace", "workspace-write", "artifacts", "mcp-tools"],
    productCapabilities: [
      { id: "repository-read", label: "Repository read", state: "available", detail: "Vraxis can enforce read-only project access for Ask, Plan, and Review." },
      { id: "isolated-build", label: "Isolated Build", state: "available", detail: "Writes are restricted to the task worktree and Vraxis-owned tools." },
      { id: "governed-terminal", label: "Governed terminal", state: "available", detail: "Agent commands use Vraxis approvals and retained PTY receipts." },
      { id: "controlled-browser", label: "Controlled browser", state: "available", detail: "The agent can inspect and actuate the isolated task browser through approvals." },
      { id: "task-evidence", label: "Task evidence", state: "available", detail: "The harness can inspect a secret-safe index of retained approvals, terminal runs, browser actions, and verification status." },
      { id: "skills", label: "Attached skills", state: "available", detail: "Task skills are injected as guidance and cannot grant extra authority." },
      { id: "model-catalog", label: "Model selection", state: "available", detail: "Models and updates are discovered from the harness." },
      { id: "retained-verification", label: "Retained verification", state: "available", detail: "Project checks run through Vraxis approvals independently of the agent transcript." },
    ],
    conformance: {
      state: "ready",
      runtimeVersion: "codex-cli 0.151.0",
      checkedAt: "2026-08-30T20:30:00.000Z",
      detail: "This runtime passed its registered adapter checks and bounded live output probe.",
      checks: [
        { id: "adapter-contract", label: "Adapter contract", state: "passed", detail: "Registered." },
        { id: "host-tool-isolation", label: "Host-tool isolation", state: "passed", detail: "Constrained." },
        { id: "live-output", label: "Live model response", state: "passed", detail: "Authenticated." },
      ],
    },
  }],
  modelProviders: [],
  skills: [],
  files: [],
  changes: [],
  events: [],
  approvals: [],
  terminalRuns: [],
  settings: { theme: "graphite-dark", defaultMode: "ask", defaultRuntimeId: "codex" },
};

export const demoState: BootstrapState = {
  contractVersion: 26,
  projects: [{
    id: "vraxis-code",
    name: "vraxis-code",
    path: "/Users/vequanclark/projects/vraxis-code",
    branch: "main",
    status: "ready",
  }],
  sessions: [],
  runtimes: [
    {
      id: "codex",
      name: "Codex CLI",
      availability: "installed",
      detail: "Ready",
      acceptsCustomModel: true,
      kind: "local-cli",
      version: "codex-cli 0.151.0",
      executable: "/usr/local/bin/codex",
      authentication: "authenticated",
      authenticationDetail: "Authenticated with ChatGPT.",
      modelDiscovery: "automatic",
      checkedAt: "2026-08-30T20:30:00.000Z",
      update: { status: "available", latestVersion: "0.152.0", detail: "Version 0.152.0 is available." },
      maintenanceActions: [
        { id: "authenticate", label: "Sign in to Codex CLI", detail: "Prepare sign in.", kind: "command", executable: "/usr/local/bin/codex", arguments: ["login"], requiresNetwork: true },
        { id: "update", label: "Update Codex CLI", detail: "Prepare update.", kind: "command", executable: "/usr/local/bin/codex", arguments: ["update"], requiresNetwork: true },
      ],
      models: [
        { id: "gpt-5.6-sol", name: "GPT-5.6-Sol", availability: "available", isDefault: true, description: "Latest frontier agentic coding model.", capabilities: ["text", "vision", "tools", "structured-output"], reasoningEfforts: ["low", "medium", "high", "xhigh", "max", "ultra"] },
        { id: "gpt-5.6-terra", name: "GPT-5.6-Terra", availability: "available", description: "Balanced agentic coding model for everyday work." },
        { id: "gpt-5.6-luna", name: "GPT-5.6-Luna", availability: "available", description: "Fast and affordable agentic coding model." },
      ],
      capabilities: ["structured-output", "local-workspace", "read-only-workspace", "workspace-write", "artifacts", "mcp-tools"],
      productCapabilities: emptyState.runtimes[0]!.productCapabilities,
      conformance: emptyState.runtimes[0]!.conformance,
    },
    {
      id: "claude-code",
      name: "Claude Code",
      availability: "missing",
      detail: "The runtime executable is missing or is not on PATH.",
      acceptsCustomModel: true,
      models: [],
      kind: "local-cli",
      authentication: "unknown",
      modelDiscovery: "unavailable",
      checkedAt: "2026-08-30T20:30:00.000Z",
      update: { status: "unknown", detail: "Install the harness before checking for updates." },
      maintenanceActions: [{ id: "install", label: "Install Claude Code", detail: "Open official installation instructions.", kind: "documentation", url: "https://docs.anthropic.com/en/docs/claude-code/setup", requiresNetwork: true }],
      capabilities: ["structured-output", "local-workspace", "read-only-workspace", "artifacts"],
    },
  ],
  modelProviders: [],
  skills: [
    {
      id: "demo-ux-fundamentals",
      name: "ux-fundamentals",
      description: "Design-system-agnostic UX guidance for product screens and flows.",
      version: "1.0.0",
      scopes: ["user"],
      runtimes: ["codex", "cursor"],
    },
  ],
  selectedProjectId: "vraxis-code",
  files: [
    { path: "apps/service/src/http/app.ts" },
    { path: "apps/web/src/App.vue" },
    { path: "packages/contracts/src/index.ts" },
    { path: "README.md" },
  ],
  changes: [],
  events: [],
  approvals: [],
  terminalRuns: [],
  verificationRuns: [],
  projectDoctor: {
    schemaVersion: 1,
    projectId: "vraxis-code",
    projectName: "vraxis-code",
    projectKind: "workspace",
    packageManager: { id: "npm", name: "npm", lockfile: "package-lock.json" },
    ecosystems: [{ id: "javascript", label: "JavaScript / TypeScript", manifest: "package.json" }],
    frameworks: [{ id: "vite", name: "Vite", ecosystem: "javascript" }, { id: "vue", name: "Vue", ecosystem: "javascript" }],
    verificationChecks: [{ id: "javascript:check", title: "Project check", category: "check", command: "npm", args: ["run", "check"], cwd: ".", required: true, timeoutMs: 900_000, source: "package.json#scripts.check" }],
    verificationSource: { kind: "discovered", browserRequired: true, browserTarget: "http://127.0.0.1:4318/" },
    devServers: [{ id: "javascript:dev", title: "Development server", command: "npm", args: ["run", "dev"], cwd: ".", suggestedUrl: "http://127.0.0.1:4318/", source: "package.json#scripts.dev" }],
    issues: [],
    ok: true,
  },
  settings: { theme: "graphite-dark", defaultMode: "ask", defaultRuntimeId: "codex" },
};
